# Generated by Django 4.0.3 on 2022-04-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=15)),
                ('roll_no', models.IntegerField()),
                ('Class',models.CharField(max_length=10)),
                #('mobile',models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
